spring.application.name=uberApp
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=T!mepass06
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.devtools.restart.enabled = true
spring.sql.init.mode=always
spring.devtools.restart.exclude = com.project.uber.uberApp/dto/**

spring.sql.init.data-locations=classpath:data.sql

server.port=8080

# Actuator configuration
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.version=1.0.0
info.app.documentation=https://codingshuttle.com/docs
management.endpoint.env.show-values=always
management.info.build.enabled=true
management.info.git.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true
logging.level.org.springframework=DEBUG


OpenAPI documentation configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secretKey = aupquqrjsofsljkhslgfhofhjhflshguslfjshgso9shgsh93050shkhs

# SMTP config
spring.mail.username = s.rajpure64@gmail.com
spring.mail.password = dglx fssu qfxg jmvs
spring.mail.host = smtp.gmail.com
spring.mail.port = 587

spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true